### ISSUE TITLE
More Concerns

### ISSUE THREAD

**Issue by bxptr** [PenguinMaster0226/discord-ext-dashboard#1]
A quick glance at the example code shows that this extension / library is highly unsafe to be used in proper bots. The reason behind this is the fact that the `Dashboard` class has to have the bot constructor passed into it. This allows for the code to to see the token of the currently running bot. Until @PenguinMaster0226 fixes this vulnerability, usage of this is highly dangerous.

That is all, have fun eating your cheese lads.

**Comment by mak0226** [comment]
If you check the discord.py documentation, you will see that there is no `token` or similar attribute in the `Bot` and `Client` classes. The `Dashboard` class is only able to access the bot's attributes, and `token` is not one of them.

**Comment by bxptr** [comment]
However, it is possible that the `Dashboard` class can slow down the bot. Having another thread running along with the bot can seriously lower the bot's latency.

**Comment by mak0226** [comment]
The `Dashboard` class does not do anything, *except* providing functions for the programmer to use, although there is one more thing. The `Dashboard` class requires the bot to have an `on_message` event with the asynchronous `Dashboard.process_request` function, which also won't slow it down.

**Comment by bxptr** [comment]
That's the main problem -- "asynchronous". Asynchronous events cause the CPU to create another thread. If people use your plugin a lot, it would cause the host computer to use more power than it needs too. Also, if they have an AWS instance running, which has no slow-down for threads (that way they earn more money), it would cause them to have to **pay** to use the extension.

**Comment by mak0226** [comment]
Asynchronous functions actually don't create new threads. It is used to use the main thread optimally, and ensure that the function will be run, whereas *synchronous* functions may not run if your program is overloaded. Even if asynchronous functions made new threads, it wouldn't be the main issue, because most discord.py functions are asynchronous, and with new threads for each of them, it would get overloaded even without any extra modules/packages.

**Comment by bxptr** [comment]
Async / Await can certainly lead to new threads being used (not necessarily created - the pool creates them at application start). It's up to the scheduler to determine if a new thread is needed. And as I see it, a call to an "awaitable" function may have internal details that increase the chances of the scheduler utilizing another thread; simply because more work means more opportunities / reasons for the scheduler to divvy out work.

**Comment by mak0226** [comment]
I don't see how async / await could slow down your program. If it actually could slow down a program, it would not be usable for a Discord bot. My discord.py bot uses at least 100s of asynchronous events everyday, without people running commands. A 100% synchronous discord.py bot would never be able to handle what an asynchronous one can. A synchronous bot would go all out in using the functions, which would result in either a crash, or excessive RAM usage.

**Comment by bxptr** [comment]
It doesn't slow down your discord bot because the server that it is run on is powerful enough to handle it. Also, the python compiler that is used on the server may have a better algorithm to convert the code to be runnable.

**Comment by mak0226** [comment]
The functions may take longer to run, but that isn't because of a memory issue. Async/await runs the functions one at a time, instead of rushing it as synchronous code would. I'm not saying that async/await is faster, but it's necessary to ensure everything runs correctly on large and heavy programs such as a discord.py bot.

**Comment by bxptr** [comment]
The problem is not about time directly. It is about the threading using up too much CPU on weaker computers, causing the program to be running slower and eventually increasing the latency.

**Comment by mak0226** [comment]
The `Dashboard` class only has *one* asynchronous function. If anything, the problem would be with discord.py since most of the functions are asynchronous. I think this is getting a little off topic, so should we close it?

**Comment by bxptr** [comment]
Sure
